import { useEffect } from 'react';

const SECTIONS = [
    {
        heading: '§1. Data Controller',
        body: 'The controller of your personal data is Shellty IT Tomasz Skorupski, os. Bursztynowe 78/78, 72-005 Warzymice, Poland, Tax ID (NIP): 8513307050, e-mail: shellty@zohomail.eu.',
    },
    {
        heading: '§2. Data We Process',
        body: 'We process the following personal data:\n• Account data — username, email address and hashed password provided upon registration\n• Profile data — profile picture and bio provided in your profile settings\n• Project and board data — projects, boards, columns, cards and their content that you create within the application\n• Collaboration data — team member assignments, card assignments and deadlines\n• Notification data — in-app notifications generated by card assignments\n• Technical data — IP addresses, login timestamps and activity logs',
    },
    {
        heading: '§3. Purpose and Legal Basis',
        body: 'Your data is processed for the following purposes:\n• Providing the project management service (Art. 6(1)(b) GDPR — performance of a contract)\n• Security and fraud prevention (Art. 6(1)(f) GDPR — legitimate interest)\n• Compliance with legal obligations (Art. 6(1)(c) GDPR)',
    },
    {
        heading: '§4. Recipients of Data',
        body: 'Your data is processed by the following sub-processor:\n• Microsoft Corporation — the application (both frontend and backend) and the database are hosted on Microsoft Azure App Service and Azure SQL Database. Microsoft applies standard contractual clauses for international data transfers.\n\nWe do not sell your personal data to third parties.',
    },
    {
        heading: '§5. Retention Period',
        body: 'Data is retained for the duration of your account. Upon account deletion, data is removed within 30 days, except where retention is required by law.',
    },
    {
        heading: '§6. Your Rights',
        body: 'Under the GDPR you have the right to:\n• Access your data and obtain a copy\n• Rectify inaccurate data\n• Erasure of data (right to be forgotten)\n• Restriction of processing\n• Data portability\n• Object to processing\n• Lodge a complaint with the supervisory authority (President of the UODO, ul. Stawki 2, 00-193 Warsaw, Poland)\n\nTo exercise your rights, contact us: shellty@zohomail.eu',
    },
    {
        heading: '§7. Cookies and Local Storage',
        body: 'The application uses only browser local storage (localStorage) for the following purposes:\n• Storing the JWT access token (session authentication, valid for 15 minutes)\n• Storing the refresh token (session persistence, valid for 7 days, invalidated on logout)\n\nWe do not use tracking or advertising cookies.',
    },
    {
        heading: '§8. Security',
        body: 'We apply technical and organisational security measures: connection encryption (HTTPS/TLS), password hashing (ASP.NET Identity), short-lived JWT tokens (15 minutes), and refresh token rotation — each token is one-time-use and invalidated upon logout.',
    },
    {
        heading: '§9. Policy Changes',
        body: 'We will notify you of significant changes to this policy by e-mail or via an in-app notice.',
    },
    {
        heading: '§10. Contact',
        body: 'Privacy enquiries: shellty@zohomail.eu',
    },
];

export default function PrivacyPolicyModal({ isOpen, onClose }) {
    useEffect(() => {
        if (!isOpen) return;
        const onKey = (e) => { if (e.key === 'Escape') onClose(); };
        document.addEventListener('keydown', onKey);
        return () => document.removeEventListener('keydown', onKey);
    }, [isOpen, onClose]);

    if (!isOpen) return null;

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div
                className="modal-box"
                onClick={e => e.stopPropagation()}
                style={{ maxWidth: '600px', maxHeight: '80vh', display: 'flex', flexDirection: 'column', padding: 0 }}
            >
                {/* Header */}
                <div style={{
                    padding: '20px 24px 16px',
                    borderBottom: '1px solid var(--border)',
                    flexShrink: 0,
                }}>
                    <p style={{ fontSize: '11px', fontWeight: '600', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--accent-cyan)', fontFamily: 'var(--font-mono)', marginBottom: '4px' }}>
                        Shellty.Kanban
                    </p>
                    <h2 style={{ fontSize: '18px', margin: 0 }}>Privacy Policy</h2>
                    <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '2px' }}>
                        Last updated: May 31, 2026
                    </p>
                </div>

                {/* Scrollable content */}
                <div style={{ overflowY: 'auto', flex: 1, padding: '20px 24px' }}>
                    {SECTIONS.map((section) => (
                        <div key={section.heading} style={{ marginBottom: '20px' }}>
                            <h3 style={{ fontSize: '13px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '6px' }}>
                                {section.heading}
                            </h3>
                            <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.7', whiteSpace: 'pre-line', margin: 0 }}>
                                {section.body}
                            </p>
                        </div>
                    ))}
                </div>

                {/* Footer */}
                <div style={{
                    padding: '16px 24px',
                    borderTop: '1px solid var(--border)',
                    flexShrink: 0,
                }}>
                    <button className="btn-primary" onClick={onClose} style={{ width: '100%' }}>
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
}
